# Version: 1.0.1
FROM ubuntu:latest
MAINTAINER Solinari "solinari27@gmail.com"
RUN apt-get update
RUN apt-get install -y python2.7
RUN apt-get install -y python-pip
RUN apt-get install -y git
#RUN echo 'Hi, I am in your container' > /usr/share/nginx/html/index.html
#EXPOSE 80
